
services:
  frontend:
    build:
      context: ./okane.frontend
    ports:
      - "3000:3000"
    environment:
      API_URL: http://app:8080
      ENCRYPTION_KEY: 8e2e5a1f4d3c6a7b9c0d1e2f3a4b5c6d7e8f90123456789abcdef0123456789
      NODE_ENV: production
    depends_on:
      - app
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=okane;Username=okane;Password=okane
      - JwtOptions__SecretKey=OBgakiY8lqC7IQJjSXowcdiKx2OEr3mB
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: okane
      POSTGRES_PASSWORD: okane
      POSTGRES_DB: okane
    ports:
      - "5432:5432"
    volumes:
      - ./Migrations:/docker-entrypoint-initdb.d/