
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://*:8080
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=okane;Username=okane;Password=okane
      - JwtOptions__SecretKey=OBgakiY8lqC7IQJjSXowcdiKx2OEr3mB
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: okane
      POSTGRES_PASSWORD: okane
      POSTGRES_DB: okane
    ports:
      - "5432:5432"
    volumes:
      - ./Migrations:/docker-entrypoint-initdb.d/