CREATE TABLE IF NOT EXISTS ledger (
	id SERIAL PRIMARY KEY,
	amount NUMERIC(19, 4) NOT NULL,
	description TEXT,
	user_id BIGINT NOT NULL REFERENCES users(id),
	origin BIGINT NOT NULL REFERENCES accounts(id)
	to BIGINT NOT NULL REFERENCES accounts(id)
	occured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);